export const AccordionData = [
    {
        name:'ning_eaglecard',
        image:'img/home/star_eagle_bk.png'
    },
    {
        name:'ning_elephantcard',
        image:'img/home/star_elephant_bk.png'
    },
    {
        name:'ning_tigercard',
        image:'img/home/star_tiger_bk.png'
    },
    {
        name:'ning_sharkcard',
        image:'img/home/star_shark_bk.png'
    },
    {
        name:'ning_hitefoxcard',
        image:'img/home/star_hitefox_bk.png'
    },
]